### ISSUE TITLE
Headers: null  failure

### ISSUE THREAD

**Issue by jaredsaul** [kksharma1618/lambda-restify#5]
Causes lambda to fail but seems to be standard for simple proxy lambda invocation:
2018-04-06T20:45:54.514Z	7fa4ae57-39db-11e8-995c-8d997d268cd1	TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at new Request (/var/task/node_modules/lambda-restify/build/lib/request.js:16:16)
at Server.handleLambdaEvent (/var/task/node_modules/lambda-restify/build/lib/server.js:101:21)

on ::: headers: null,

**Comment by jaredsaul** [comment]
quick fix is the following;
event.headers=[{"dummy":"dumber"}]; or similar
